apiVersion: 1

datasources:
  - name: MySQL-SnapMirror
    type: mysql
    access: proxy
    url: mysql:3306
    database: snapmirror_monitoring
    user: snapmirror_user
    secureJsonData:
      password: SnapMirror123!
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    editable: true
